# Data Science Capstone Project

In [1]:
# Importing Necessary Python Library
import pandas as pd               # Read the dataset, create the data frame       
import numpy as np                # Numerical imputation
from tabulate import tabulate     # To print the table
import warnings                   # To Control warnings
warnings.filterwarnings("ignore")

### Data Processing

### Load the necessary dataset / Importing the required dataset

In [2]:
# 01. Appearance Data
appearance = pd.read_excel('appearances.xlsx')
appearance

,appearance_id,game_id,player_id,date,player_name,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,2224728_119169,2224728,119169,2012-07-13,Aron Johannsson,DK1,0,0,0,0,90
1,2224732_161244,2224732,161244,2012-07-14,Conor O'Brien,DK1,0,0,1,0,90
2,2224729_39467,2224729,39467,2012-07-15,Clarence Goodson,DK1,0,0,0,0,90
3,2232104_119169,2232104,119169,2012-07-19,Aron Johannsson,ELQ,0,0,0,0,74
4,2219794_39475,2219794,39475,2012-07-22,Sacha Kljestan,BESC,0,0,0,0,3
...,...,...,...,...,...,...,...,...,...,...,...
3563,3415291_537467,3415291,537467,2020-09-26,Joseph Efford,BE1,0,0,1,0,77
3564,3415296_367423,3415296,367423,2020-09-26,Chris Durkin,BE1,1,0,0,0,84
3565,3431983_478940,3431983,478940,2020-09-26,Reggie Cannon,PO1,0,0,0,0,90
3566,3450575_361104,3450575,361104,2020-09-26,Sergino Dest,NL1,0,0,0,0,6
3567,3412904_124732,3412904,124732,2020-09-27,John Anthony Brooks,L1,1,0,0,0,90

In [3]:
appearance.isnull().sum()

appearance_id     0
game_id           0
player_id         0
date              0
player_name       0
competition_id    0
yellow_cards      0
red_cards         0
goals             0
assists           0
minutes_played    0
dtype: int64

In [4]:
# 02. Game_event Data
game_event = pd.read_excel('game_events.xlsx')
game_event

,game_event_id,date,game_id,minute,type,player_id,description,player_in_id,player_assist_id
0,c6a3c088ed8a38d4ce074dd73b20d3da,2012-08-19,2221641,62,Substitutions,1335,", Not reported",45668.0,NaN
1,02d605a5c2dc4f9a6721daa583fa5405,2012-08-26,2222536,54,Cards,1321,"1. Yellow card , Foul",NaN,NaN
2,b56c2e2e087cddb3cfe9e3d340975df9,2012-11-18,2222707,79,Substitutions,104203,", Tactical",25740.0,NaN
3,4a15d1fff4f476f48bb60092c61641d5,2012-11-23,2222721,72,Substitutions,104203,", Tactical",15583.0,NaN
4,daa97877f7edf2fda885b411d7197921,2013-05-17,2222782,63,Goals,104203,", Right-footed shot, 1. Goal of the Season Ass...",NaN,15077.0
...,...,...,...,...,...,...,...,...,...
1844,4acebccbc824e45d51045d8c5e164341,2023-10-31,4194147,3,Goals,355369,", Left-footed shot, 1. Tournament Goal Assist:...",NaN,284010.0
1845,159ad5633cf9d7c3a97b593efb6c3269,2023-10-31,4194147,9,Goals,355369,", Right-footed shot, 2. Tournament Goal Assist...",NaN,629588.0
1846,daa31f19aab26eec375884aef73c73b3,2023-10-31,4194147,65,Substitutions,355369,", Tactical",544148.0,NaN
1847,869a13060604e769290dafe0b1f14483,2023-11-01,4194152,70,Substitutions,504215,", Tactical",406640.0,NaN
1848,6b7ed06f13c1f67f0d7359c310f20ba0,2023-10-31,4194154,76,Substitutions,103064,", Tactical",378874.0,NaN

In [5]:
game_event.isnull().sum()

game_event_id          0
date                   0
game_id                0
minute                 0
type                   0
player_id              0
description          933
player_in_id         694
player_assist_id    1709
dtype: int64

In [6]:
game_event=game_event.drop(['player_in_id','player_assist_id'],axis=1) # this two column removed

In [7]:
game_event["description"].mode()

0    , Tactical
Name: description, dtype: object

In [8]:
game_event["description"] = game_event["description"].fillna(", Tactical")

In [9]:
game_event.isnull().sum()

game_event_id    0
date             0
game_id          0
minute           0
type             0
player_id        0
description      0
dtype: int64

In [10]:
# 03. Game_Lineup
game_Lineup = pd.read_excel('game_lineups.xlsx')
game_Lineup

,game_lineups_id,game_id,type,number,player_id,player_name,team_captain,position
0,f2570d1504fc02f4b6c7608e8dcf89a3,4087925,substitutes,34,242284,Ethan Horvath,0,Goalkeeper
1,f5f0da93ea8e1d8bdd799658e7c8f7cb,4087928,starting_lineup,13,145466,Tim Ream,0,Centre-Back
2,31a4d12ec23d604779d909d26c1b5410,4087929,substitutes,26,578539,Chris Richards,0,Centre-Back
3,776dcbef98651450db76723cb7e3b4df,4087935,substitutes,26,578539,Chris Richards,0,Centre-Back
4,6a35ef7495303f29e7f85dbd54547fb1,4087936,starting_lineup,13,145466,Tim Ream,1,Centre-Back
...,...,...,...,...,...,...,...,...
214,ec3d266094f99ca0a8847de827e37105,4194152,starting_lineup,7,504215,Giovanni Reyna,0,Right Winger
215,667840cda9bdf3b0344b8e99b306cf38,4194152,starting_lineup,23,124732,John Anthony Brooks,0,Centre-Back
216,1c5d2f60ee777760f8a757aa10c42bb1,4194154,starting_lineup,13,103064,Terrence Boyd,0,Centre-Forward
217,99032084fd00ffbfee52c541a9f960ab,4204000,substitutes,14,315762,Luca de la Torre,0,Central Midfield
218,5c9eaf6ebb621d43a0d6fd6a9e607ef9,4220942,substitutes,13,145466,Tim Ream,0,Centre-Back

In [11]:
game_Lineup.isnull().sum()

game_lineups_id    0
game_id            0
type               0
number             0
player_id          0
player_name        0
team_captain       0
position           0
dtype: int64

In [12]:
# 04. Games Data
games = pd.read_excel('games.xlsx')
games

,game_id,competition_id,season,round,date,home_club_goals,away_club_goals,home_club_position,away_club_position,home_club_manager_name,away_club_manager_name,stadium,attendance,referee,home_club_formation,away_club_formation,home_club_name,away_club_name,aggregate,competition_type
0,2222734,RU1,2012,19. Matchday,2012-12-07,2,3,11.0,10.0,Miodrag Bozovic,Slavoljub Muslin,Olimp-2,5700.0,Sergey Kuznetsov,NaN,NaN,FK Rostov,FK Krasnodar,02:03:00,domestic_league
1,2224572,DK1,2012,3. Matchday,2012-07-28,1,2,12.0,1.0,Jess Thorup,Lars Sondergaard,Blue Water Arena,5345.0,Michael Svendsen,NaN,NaN,Esbjerg fB,Sonderjyske Fc,01:02:00,domestic_league
2,2224628,DK1,2012,22. Matchday,2013-03-08,2,0,3.0,10.0,Colin Todd,Lars Sondergaard,Cepheus Park Randers,3481.0,Jakob Kehlet,NaN,NaN,Randers Fodbold Club,Sonderjyske Fc,02:00:00,domestic_league
3,2224655,DK1,2012,22. Matchday,2013-03-10,0,3,6.0,12.0,Peter Rensen,Auri Skarbalius,Ceres Park,7967.0,Kenn Hansen,NaN,NaN,Aarhus Gymnastik Forening,BRA NDBYERNES,00:03:00,domestic_league
4,2224729,DK1,2012,1. Matchday,2012-07-15,0,1,9.0,5.0,Auri Skarbalius,Troels Bech,Brondby Stadium,10806.0,Lars Christoffersen,NaN,NaN,Brondby IF,Odense Boldklub,00:01:00,domestic_league
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3263,3296153,NLP,2019,Round of 16,2020-01-22,7,0,NaN,NaN,Erik ten Hag,Eric Meijers,Johan Cruijff ArenA,52017.0,Richard Martens,NaN,NaN,AFC Ajax Amsterdam,NaN,07:00:00,domestic_cup
3264,2875216,DK1,2017,19. Matchday,2017-12-10,3,2,3.0,4.0,Kasper Hjulmand,Thomas Thomasberg,Right to Dream Park,2843.0,Michael Tykgaard,NaN,NaN,Football Club Nords,Hobro IK,03:02:00,domestic_league
3265,3099247,BE1,2018,11. Matchday,2018-10-20,3,1,9.0,7.0,Glen De Boeck,Marc Brys,Guldensporenstadion,6143.0,Wesley Alen,NaN,NaN,Koninklijke Voetbalclub Kortrijk,Koninklijke Sint-Truidense Voetbalvereniging,03:01:00,domestic_league
3266,2872273,GB1,2017,16. Matchday,2017-12-09,5,1,6.0,15.0,Mauricio Pochettino,Mark Hughes,Wembley Stadium,62202.0,Roger East,NaN,NaN,Tottenham Hotspur Football Club,Stoke City,05:01:00,domestic_league
3267,2517322,FAC,2014,Third Round,2015-01-04,3,1,NaN,NaN,Mark Hughes,Kevin Wilkin,bet365 Stadium,19423.0,Simon Hooper,NaN,NaN,Stoke City,NaN,03:01:00,domestic_cup

In [13]:
games.isnull().sum()

game_id                      0
competition_id               0
season                       0
round                        0
date                         0
home_club_goals              0
away_club_goals              0
home_club_position         479
away_club_position         479
home_club_manager_name       5
away_club_manager_name       5
stadium                      0
attendance                 115
referee                      2
home_club_formation       3268
away_club_formation       3268
home_club_name             110
away_club_name              63
aggregate                    0
competition_type             0
dtype: int64

In [14]:
games=games.drop(['home_club_formation','away_club_formation'],axis=1)

In [15]:
games.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3268 entries, 0 to 3267
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   game_id                 3268 non-null   int64
 1   competition_id          3268 non-null   object
 2   season                  3268 non-null   int64
 3   round                   3268 non-null   object
 4   date                    3268 non-null   datetime64[ns]
 5   home_club_goals         3268 non-null   int64
 6   away_club_goals         3268 non-null   int64
 7   home_club_position      2789 non-null   float64
 8   away_club_position      2789 non-null   float64
 9   home_club_manager_name  3263 non-null   object
 10  away_club_manager_name  3263 non-null   object
 11  stadium                 3268 non-null   object
 12  attendance              3153 non-null   float64
 13  referee                 3266 non-null   object
 14  home_club_name          3158 non-null   object
 15  away_club_name          3205 non-null   object
 16  aggregate               3268 non-null   object
 17  competition_type        3268 non-null   object
dtypes: datetime64[ns](1), float64(3), int64(4), object(10)
memory usage: 459.7+ KB

In [16]:
x = games["home_club_position"].mean()
games["home_club_position"] = games["home_club_position"].fillna(x)

In [17]:
x = games["away_club_position"].mean()
games["away_club_position"] = games["away_club_position"].fillna(x)

In [18]:
games["home_club_manager_name"].mode()

0    Mark Hughes
Name: home_club_manager_name, dtype: object

In [19]:
games["home_club_manager_name"] = games["home_club_manager_name"].fillna("Mark Hughes")

In [20]:
games["away_club_manager_name"].mode()

0    Mark Hughes
Name: away_club_manager_name, dtype: object

In [21]:
games["away_club_manager_name"] = games["away_club_manager_name"].fillna("Mark Hughes")

In [22]:
x = games["attendance"].mean()
games["attendance"] = games["attendance"].fillna(x)

In [23]:
games["referee"].mode()

0    Dr. Felix Brych
Name: referee, dtype: object

In [24]:
games["referee"] = games["referee"].fillna("Dr. Felix Brych")

In [25]:
games["home_club_name"].mode()

0    Borussia Verein fÃ¼r LeibesÃ¼bung 1900 e.V.
Name: home_club_name, dtype: object

In [26]:
games["home_club_name"] = games["home_club_name"].fillna("Borussia Verein fÃ¼r LeibesÃ¼bung 1900 e.V.")

In [27]:
games["away_club_name"].mode()

0    Borussia Dortmund
Name: away_club_name, dtype: object

In [28]:
games["away_club_name"] = games["away_club_name"].fillna("Borussia Dortmund")

In [29]:
games.isnull().sum()

game_id                   0
competition_id            0
season                    0
round                     0
date                      0
home_club_goals           0
away_club_goals           0
home_club_position        0
away_club_position        0
home_club_manager_name    0
away_club_manager_name    0
stadium                   0
attendance                0
referee                   0
home_club_name            0
away_club_name            0
aggregate                 0
competition_type          0
dtype: int64

In [30]:
# 05. Players Data
players = pd.read_excel('players.xlsx')
players

,player_id,name,last_season,current_club_id,player_code,country_of_birth,date_of_birth,sub_position,position,foot,height_in_cm,market_value_in_eur,highest_market_value_in_eur,contract_expiration_date,agent_name
0,124732,John Anthony Brooks,2023,533,john-anthony-brooks,Germany,1993-01-28,Centre-Back,Defender,left,194.0,2000000.0,15000000.0,2024-06-30,ROGON
1,223047,Emerson Hyndman,2018,903,emerson-hyndman,United States,1996-04-09,Central Midfield,Midfield,right,170.0,800000.0,1800000.0,NaT,OmniSports
2,307781,Lynden Gooch,2016,289,lynden-gooch,United States,1995-12-24,Right Winger,Attack,right,173.0,1000000.0,1000000.0,2024-06-30,Unique Sports Group
3,370846,Timothy Weah,2023,506,timothy-weah,United States,2000-02-22,Right Midfield,Midfield,right,183.0,14000000.0,15000000.0,2028-06-30,BS Group - BS Law
4,484756,Djordje Mihailovic,2023,1090,djordje-mihailovic,United States,1998-11-10,Attacking Midfield,Midfield,NaN,178.0,5000000.0,6000000.0,2026-06-30,YMU Management Ltd.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147,273570,Desevio Payne,2020,1283,desevio-payne,United States,1995-11-30,Right-Back,Defender,right,182.0,NaN,400000.0,NaT,NaN
148,111783,Alejandro Bedoya,2015,995,alejandro-bedoya,United States,1987-04-29,Central Midfield,Midfield,right,182.0,300000.0,2500000.0,2023-12-31,YMU Group
149,160670,Joe Gyau,2014,16,joe-gyau,United States,1992-09-16,Left Winger,Attack,both,175.0,400000.0,600000.0,2023-12-31,BR Group Management
150,3476,Brad Friedel,2014,148,brad-friedel,United States,1971-05-18,Goalkeeper,Goalkeeper,NaN,NaN,NaN,4000000.0,NaT,NaN
151,504215,Giovanni Reyna,2023,16,giovanni-reyna,England,2002-11-13,Attacking Midfield,Midfield,right,185.0,25000000.0,42000000.0,2025-06-30,Wasserman

In [31]:
players.isnull().sum()

player_id                       0
name                            0
last_season                     0
current_club_id                 0
player_code                     0
country_of_birth                0
date_of_birth                   0
sub_position                    0
position                        0
foot                           11
height_in_cm                    3
market_value_in_eur            38
highest_market_value_in_eur     4
contract_expiration_date       46
agent_name                     45
dtype: int64

In [32]:
players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 152 entries, 0 to 151
Data columns (total 15 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   player_id                    152 non-null    int64
 1   name                         152 non-null    object
 2   last_season                  152 non-null    int64
 3   current_club_id              152 non-null    int64
 4   player_code                  152 non-null    object
 5   country_of_birth             152 non-null    object
 6   date_of_birth                152 non-null    datetime64[ns]
 7   sub_position                 152 non-null    object
 8   position                     152 non-null    object
 9   foot                         141 non-null    object
 10  height_in_cm                 149 non-null    float64
 11  market_value_in_eur          114 non-null    float64
 12  highest_market_value_in_eur  148 non-null    float64
 13  contract_expiration_date     106 non-null    datetime64[ns]
 14  agent_name                   107 non-null    object
dtypes: datetime64[ns](2), float64(3), int64(3), object(7)
memory usage: 17.9+ KB

In [33]:
players["foot"].mode()

0    right
Name: foot, dtype: object

In [34]:
players["foot"] = players["foot"].fillna("right")

In [35]:
x = players["height_in_cm"].mean()
players["height_in_cm"] = players["height_in_cm"].fillna(x)

In [36]:
x = players["market_value_in_eur"].mean()
players["market_value_in_eur"] = players["market_value_in_eur"].fillna(x)

In [37]:
x = players["highest_market_value_in_eur"].mean()
players["highest_market_value_in_eur"] = players["highest_market_value_in_eur"].fillna(x)

In [38]:
players["contract_expiration_date"].mode()

0   2025-06-30
Name: contract_expiration_date, dtype: datetime64[ns]

In [39]:
players["contract_expiration_date"] = players["contract_expiration_date"].fillna("2025-06-30")

In [40]:
players["agent_name"].mode()

0    Wasserman
Name: agent_name, dtype: object

In [41]:
players["agent_name"] = players["agent_name"].fillna("Wasserman")

In [42]:
players.isnull().sum()

player_id                      0
name                           0
last_season                    0
current_club_id                0
player_code                    0
country_of_birth               0
date_of_birth                  0
sub_position                   0
position                       0
foot                           0
height_in_cm                   0
market_value_in_eur            0
highest_market_value_in_eur    0
contract_expiration_date       0
agent_name                     0
dtype: int64

### CONNECTING THE CLEANED DATA INTO MYSQL

In [43]:
pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\akhil james\anaconda3\lib\site-packages (8.3.0)
Note: you may need to restart the kernel to use updated packages.

In [44]:
import mysql.connector as sql

In [45]:
from sqlalchemy import create_engine

In [46]:
db = sql.connect(host = "localhost", user = "root", password = "AKHILAK123", database = "school")

In [47]:
mycursor=db.cursor()

In [48]:
mycursor.execute("create database Football_Data")

In [49]:
engine = create_engine("mysql+pymysql://{user}:{pw}@{host}/{db}".
                       format(host='localhost', db='Football_Data', user='root', pw='AKHILAK123'))

### CONNECTING ALL THE FILES TO MYSQL

In [50]:
appearance.to_sql("appearance", engine,index = False)

3568

In [51]:
game_event.to_sql("game_event", engine,index = False)

1849

In [52]:
game_Lineup.to_sql("game_Lineup", engine,index = False)

219

In [53]:
games.to_sql("games", engine,index = False)

3268

In [54]:
players.to_sql("players", engine,index = False)

152

### Merging the Data Files

In [55]:
df = pd.merge(appearance,players, on='player_id', how = 'left')
df

,appearance_id,game_id,player_id,date,player_name,competition_id,yellow_cards,red_cards,goals,assists,...,country_of_birth,date_of_birth,sub_position,position,foot,height_in_cm,market_value_in_eur,highest_market_value_in_eur,contract_expiration_date,agent_name
0,2224728_119169,2224728,119169,2012-07-13,Aron Johannsson,DK1,0,0,0,0,...,United States,1990-11-10,Centre-Forward,Attack,right,184.0,4.000000e+05,4000000.0,2024-12-31,CAA Stellar
1,2224732_161244,2224732,161244,2012-07-14,Conor O'Brien,DK1,0,0,1,0,...,United States,1988-10-20,Defensive Midfield,Midfield,right,177.0,3.694298e+06,750000.0,2025-06-30,Wasserman
2,2224729_39467,2224729,39467,2012-07-15,Clarence Goodson,DK1,0,0,0,0,...,United States,1982-05-17,Centre-Back,Defender,right,193.0,3.694298e+06,1850000.0,2025-06-30,Wasserman
3,2232104_119169,2232104,119169,2012-07-19,Aron Johannsson,ELQ,0,0,0,0,...,United States,1990-11-10,Centre-Forward,Attack,right,184.0,4.000000e+05,4000000.0,2024-12-31,CAA Stellar
4,2219794_39475,2219794,39475,2012-07-22,Sacha Kljestan,BESC,0,0,0,0,...,United States,1985-09-09,Attacking Midfield,Midfield,both,185.0,3.694298e+06,3000000.0,2025-06-30,Wasserman
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3563,3415291_537467,3415291,537467,2020-09-26,Joseph Efford,BE1,0,0,1,0,...,United States,1996-08-29,Centre-Forward,Attack,right,176.0,3.000000e+05,600000.0,2026-06-30,TOP Agency
3564,3415296_367423,3415296,367423,2020-09-26,Chris Durkin,BE1,1,0,0,0,...,United States,2000-02-08,Defensive Midfield,Midfield,right,182.0,1.200000e+06,1200000.0,2024-12-31,Mega Sports
3565,3431983_478940,3431983,478940,2020-09-26,Reggie Cannon,PO1,0,0,0,0,...,United States,1998-06-11,Right-Back,Defender,right,180.0,4.000000e+06,4000000.0,2025-06-30,YMU Management Ltd.
3566,3450575_361104,3450575,361104,2020-09-26,Sergino Dest,NL1,0,0,0,0,...,Netherlands,2000-11-03,Right-Back,Defender,right,171.0,1.000000e+07,30000000.0,2024-06-30,Joes Blakborn
3567,3412904_124732,3412904,124732,2020-09-27,John Anthony Brooks,L1,1,0,0,0,...,Germany,1993-01-28,Centre-Back,Defender,left,194.0,2.000000e+06,15000000.0,2024-06-30,ROGON

In [56]:
df1 = pd.merge(df,game_event,on='game_id', how = 'left')
df1

,appearance_id,game_id,player_id_x,date_x,player_name,competition_id,yellow_cards,red_cards,goals,assists,...,market_value_in_eur,highest_market_value_in_eur,contract_expiration_date,agent_name,game_event_id,date_y,minute,type,player_id_y,description
0,2224728_119169,2224728,119169,2012-07-13,Aron Johannsson,DK1,0,0,0,0,...,4.000000e+05,4000000.0,2024-12-31,CAA Stellar,NaN,NaT,NaN,NaN,NaN,NaN
1,2224732_161244,2224732,161244,2012-07-14,Conor O'Brien,DK1,0,0,1,0,...,3.694298e+06,750000.0,2025-06-30,Wasserman,d9f02a9d767f319e58909ba1e1de6d23,2012-07-14,50.0,Goals,161244.0,", Long distance kick, 1. Goal of the Season As..."
2,2224729_39467,2224729,39467,2012-07-15,Clarence Goodson,DK1,0,0,0,0,...,3.694298e+06,1850000.0,2025-06-30,Wasserman,NaN,NaT,NaN,NaN,NaN,NaN
3,2232104_119169,2232104,119169,2012-07-19,Aron Johannsson,ELQ,0,0,0,0,...,4.000000e+05,4000000.0,2024-12-31,CAA Stellar,2ab0ea7af8313c0da07c723728bb6a49,2012-07-19,74.0,Substitutions,119169.0,", Not reported"
4,2219794_39475,2219794,39475,2012-07-22,Sacha Kljestan,BESC,0,0,0,0,...,3.694298e+06,3000000.0,2025-06-30,Wasserman,NaN,NaT,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3804,3415291_537467,3415291,537467,2020-09-26,Joseph Efford,BE1,0,0,1,0,...,3.000000e+05,600000.0,2026-06-30,TOP Agency,2c1bc4101fb8b426e84b9b5d55eb5783,2020-09-26,77.0,Substitutions,537467.0,", Tactical"
3805,3415296_367423,3415296,367423,2020-09-26,Chris Durkin,BE1,1,0,0,0,...,1.200000e+06,1200000.0,2024-12-31,Mega Sports,b3d9d733681d01939841c363789f9642,2020-09-26,84.0,Substitutions,367423.0,", Tactical"
3806,3431983_478940,3431983,478940,2020-09-26,Reggie Cannon,PO1,0,0,0,0,...,4.000000e+06,4000000.0,2025-06-30,YMU Management Ltd.,NaN,NaT,NaN,NaN,NaN,NaN
3807,3450575_361104,3450575,361104,2020-09-26,Sergino Dest,NL1,0,0,0,0,...,1.000000e+07,30000000.0,2024-06-30,Joes Blakborn,NaN,NaT,NaN,NaN,NaN,NaN
3808,3412904_124732,3412904,124732,2020-09-27,John Anthony Brooks,L1,1,0,0,0,...,2.000000e+06,15000000.0,2024-06-30,ROGON,NaN,NaT,NaN,NaN,NaN,NaN

In [57]:
df2 = pd.merge(df1,game_Lineup, on='game_id', how = 'left')
df2

,appearance_id,game_id,player_id_x,date_x,player_name_x,competition_id,yellow_cards,red_cards,goals,assists,...,type_x,player_id_y,description,game_lineups_id,type_y,number,player_id,player_name_y,team_captain,position_y
0,2224728_119169,2224728,119169,2012-07-13,Aron Johannsson,DK1,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2224732_161244,2224732,161244,2012-07-14,Conor O'Brien,DK1,0,0,1,0,...,Goals,161244.0,", Long distance kick, 1. Goal of the Season As...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2224729_39467,2224729,39467,2012-07-15,Clarence Goodson,DK1,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2232104_119169,2232104,119169,2012-07-19,Aron Johannsson,ELQ,0,0,0,0,...,Substitutions,119169.0,", Not reported",NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2219794_39475,2219794,39475,2012-07-22,Sacha Kljestan,BESC,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3804,3415291_537467,3415291,537467,2020-09-26,Joseph Efford,BE1,0,0,1,0,...,Substitutions,537467.0,", Tactical",NaN,NaN,NaN,NaN,NaN,NaN,NaN
3805,3415296_367423,3415296,367423,2020-09-26,Chris Durkin,BE1,1,0,0,0,...,Substitutions,367423.0,", Tactical",NaN,NaN,NaN,NaN,NaN,NaN,NaN
3806,3431983_478940,3431983,478940,2020-09-26,Reggie Cannon,PO1,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3807,3450575_361104,3450575,361104,2020-09-26,Sergino Dest,NL1,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3808,3412904_124732,3412904,124732,2020-09-27,John Anthony Brooks,L1,1,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [58]:
df3 = pd.merge(df2,games, on='game_id', how = 'left')
df3

,appearance_id,game_id,player_id_x,date_x,player_name_x,competition_id_x,yellow_cards,red_cards,goals,assists,...,away_club_position,home_club_manager_name,away_club_manager_name,stadium,attendance,referee,home_club_name,away_club_name,aggregate,competition_type
0,2224728_119169,2224728,119169,2012-07-13,Aron Johannsson,DK1,0,0,0,0,...,7.000000,Peter Rensen,Kent Nielsen,Ceres Park,9728.00000,Michael Svendsen,Aarhus Gymnastik Forening,Aalborg BK,01:01:00,domestic_league
1,2224732_161244,2224732,161244,2012-07-14,Conor O'Brien,DK1,0,0,1,0,...,12.000000,Lars Sondergaard,Colin Todd,Sydbank Park,2995.00000,Claus Bo Larsen,Sonderjyske Fc,Randers Fodbold Club,06:01:00,domestic_league
2,2224729_39467,2224729,39467,2012-07-15,Clarence Goodson,DK1,0,0,0,0,...,5.000000,Auri Skarbalius,Troels Bech,Brondby Stadium,10806.00000,Lars Christoffersen,Brondby IF,Odense Boldklub,00:01:00,domestic_league
3,2232104_119169,2232104,119169,2012-07-19,Aron Johannsson,ELQ,0,0,0,0,...,9.506633,Peter Rensen,Temur Shalamberidze,Ceres Park,9000.00000,Boako Jovanetic,Aarhus Gymnastik Forening,Borussia Dortmund,01:02:00,international_cup
4,2219794_39475,2219794,39475,2012-07-22,Sacha Kljestan,BESC,0,0,0,0,...,9.506633,John van den Brom,Peter Maes,Constant Vanden Stock Stadion,14485.00000,Laurent Colemonts,Royal Sporting Club Anderlecht,KSC Lokeren (- 2020),03:02:00,other
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3804,3415291_537467,3415291,537467,2020-09-26,Joseph Efford,BE1,0,0,1,0,...,18.000000,Hernan Losada,Nicky Hayen,Olympisch Stadion,3200.00000,Wesli De Cremer,Beerschot V.A.,SK Beveren,03:02:00,domestic_league
3805,3415296_367423,3415296,367423,2020-09-26,Chris Durkin,BE1,1,0,0,0,...,16.000000,Wouter Vrancken,Kevin Muscat,AFAS Stadion,5185.00000,Nathan Verboomen,Yellow-Red Koninklijke Voetbalclub Mechelen,Koninklijke Sint-Truidense Voetbalvereniging,02:00:00,domestic_league
3806,3431983_478940,3431983,478940,2020-09-26,Reggie Cannon,PO1,0,0,0,0,...,1.000000,Vasco Seabra,Sergio Conceicao,EstÃ¡dio do Bessa,29384.73105,LuÃ­s Godinho,Boavista Futebol Clube,Futebol Clube do Porto,00:05:00,domestic_league
3807,3450575_361104,3450575,361104,2020-09-26,Sergino Dest,NL1,0,0,0,0,...,6.000000,Erik ten Hag,Thomas Letsch,Johan Cruijff ArenA,15000.00000,Pol van Boekel,AFC Ajax Amsterdam,Stichting Betaald Voetbal Vitesse Arnhem,02:01:00,domestic_league
3808,3412904_124732,3412904,124732,2020-09-27,John Anthony Brooks,L1,1,0,0,0,...,13.000000,Christian Streich,Oliver Glasner,Dreisamstadion,3200.00000,Soren Storks,Sport-Club Freiburg,Verein Fur leibesubungen Wolfsburg,01:01:00,domestic_league

In [59]:
df3.isnull().sum()

appearance_id                     0
game_id                           0
player_id_x                       0
date_x                            0
player_name_x                     0
competition_id_x                  0
yellow_cards                      0
red_cards                         0
goals                             0
assists                           0
minutes_played                    0
name                              0
last_season                       0
current_club_id                   0
player_code                       0
country_of_birth                  0
date_of_birth                     0
sub_position                      0
position_x                        0
foot                              0
height_in_cm                      0
market_value_in_eur               0
highest_market_value_in_eur       0
contract_expiration_date          0
agent_name                        0
game_event_id                  2470
date_y                         2470
minute                         2470
type_x                         2470
player_id_y                    2470
description                    2470
game_lineups_id                3809
type_y                         3809
number                         3809
player_id                      3809
player_name_y                  3809
team_captain                   3809
position_y                     3809
competition_id_y                  0
season                            0
round                             0
date                              0
home_club_goals                   0
away_club_goals                   0
home_club_position                0
away_club_position                0
home_club_manager_name            0
away_club_manager_name            0
stadium                           0
attendance                        0
referee                           0
home_club_name                    0
away_club_name                    0
aggregate                         0
competition_type                  0
dtype: int64

In [60]:
df3=df3.drop(['competition_id_y','date_y', 'minute', 'player_id_y',
    'game_lineups_id', 'type_y', 'number', 'player_id',
       'player_name_y', 'team_captain', 'position_y'],axis=1)

In [63]:
df3["description"].mode()

0    , Tactical
Name: description, dtype: object

In [64]:
df3["description"] = df3["description"].fillna(", Tactical")

In [66]:
df3["type_x"].mode()

0    Substitutions
Name: type_x, dtype: object

In [67]:
df3["type_x"] = df3["type_x"].fillna("Substitutions")

In [68]:
df3.isnull().sum()

appearance_id                     0
game_id                           0
player_id_x                       0
date_x                            0
player_name_x                     0
competition_id_x                  0
yellow_cards                      0
red_cards                         0
goals                             0
assists                           0
minutes_played                    0
name                              0
last_season                       0
current_club_id                   0
player_code                       0
country_of_birth                  0
date_of_birth                     0
sub_position                      0
position_x                        0
foot                              0
height_in_cm                      0
market_value_in_eur               0
highest_market_value_in_eur       0
contract_expiration_date          0
agent_name                        0
game_event_id                  2470
type_x                            0
description                       0
season                            0
round                             0
date                              0
home_club_goals                   0
away_club_goals                   0
home_club_position                0
away_club_position                0
home_club_manager_name            0
away_club_manager_name            0
stadium                           0
attendance                        0
referee                           0
home_club_name                    0
away_club_name                    0
aggregate                         0
competition_type                  0
dtype: int64

### CONNECTING THE MERGED DATA TO MYSQL

In [69]:
df3.to_sql("Merged_Data", engine, index = False)

3809

In [70]:
df=df3  # Changing the variable name to convenient name

In [71]:
df.to_excel('FOOTBALL_DATA_CLEANED.xlsx', index=False)

In [72]:
df.head()

,appearance_id,game_id,player_id_x,date_x,player_name_x,competition_id_x,yellow_cards,red_cards,goals,assists,...,away_club_position,home_club_manager_name,away_club_manager_name,stadium,attendance,referee,home_club_name,away_club_name,aggregate,competition_type
0,2224728_119169,2224728,119169,2012-07-13,Aron Johannsson,DK1,0,0,0,0,...,7.000000,Peter Rensen,Kent Nielsen,Ceres Park,9728.0,Michael Svendsen,Aarhus Gymnastik Forening,Aalborg BK,01:01:00,domestic_league
1,2224732_161244,2224732,161244,2012-07-14,Conor O'Brien,DK1,0,0,1,0,...,12.000000,Lars Sondergaard,Colin Todd,Sydbank Park,2995.0,Claus Bo Larsen,Sonderjyske Fc,Randers Fodbold Club,06:01:00,domestic_league
2,2224729_39467,2224729,39467,2012-07-15,Clarence Goodson,DK1,0,0,0,0,...,5.000000,Auri Skarbalius,Troels Bech,Brondby Stadium,10806.0,Lars Christoffersen,Brondby IF,Odense Boldklub,00:01:00,domestic_league
3,2232104_119169,2232104,119169,2012-07-19,Aron Johannsson,ELQ,0,0,0,0,...,9.506633,Peter Rensen,Temur Shalamberidze,Ceres Park,9000.0,Boako Jovanetic,Aarhus Gymnastik Forening,Borussia Dortmund,01:02:00,international_cup
4,2219794_39475,2219794,39475,2012-07-22,Sacha Kljestan,BESC,0,0,0,0,...,9.506633,John van den Brom,Peter Maes,Constant Vanden Stock Stadion,14485.0,Laurent Colemonts,Royal Sporting Club Anderlecht,KSC Lokeren (- 2020),03:02:00,other

In [73]:
df.tail()

,appearance_id,game_id,player_id_x,date_x,player_name_x,competition_id_x,yellow_cards,red_cards,goals,assists,...,away_club_position,home_club_manager_name,away_club_manager_name,stadium,attendance,referee,home_club_name,away_club_name,aggregate,competition_type
3804,3415291_537467,3415291,537467,2020-09-26,Joseph Efford,BE1,0,0,1,0,...,18.0,Hernan Losada,Nicky Hayen,Olympisch Stadion,3200.00000,Wesli De Cremer,Beerschot V.A.,SK Beveren,03:02:00,domestic_league
3805,3415296_367423,3415296,367423,2020-09-26,Chris Durkin,BE1,1,0,0,0,...,16.0,Wouter Vrancken,Kevin Muscat,AFAS Stadion,5185.00000,Nathan Verboomen,Yellow-Red Koninklijke Voetbalclub Mechelen,Koninklijke Sint-Truidense Voetbalvereniging,02:00:00,domestic_league
3806,3431983_478940,3431983,478940,2020-09-26,Reggie Cannon,PO1,0,0,0,0,...,1.0,Vasco Seabra,Sergio Conceicao,EstÃ¡dio do Bessa,29384.73105,LuÃ­s Godinho,Boavista Futebol Clube,Futebol Clube do Porto,00:05:00,domestic_league
3807,3450575_361104,3450575,361104,2020-09-26,Sergino Dest,NL1,0,0,0,0,...,6.0,Erik ten Hag,Thomas Letsch,Johan Cruijff ArenA,15000.00000,Pol van Boekel,AFC Ajax Amsterdam,Stichting Betaald Voetbal Vitesse Arnhem,02:01:00,domestic_league
3808,3412904_124732,3412904,124732,2020-09-27,John Anthony Brooks,L1,1,0,0,0,...,13.0,Christian Streich,Oliver Glasner,Dreisamstadion,3200.00000,Soren Storks,Sport-Club Freiburg,Verein Fur leibesubungen Wolfsburg,01:01:00,domestic_league

In [74]:
df.shape

(3809, 44)

In [75]:
df.isnull().sum()

appearance_id                     0
game_id                           0
player_id_x                       0
date_x                            0
player_name_x                     0
competition_id_x                  0
yellow_cards                      0
red_cards                         0
goals                             0
assists                           0
minutes_played                    0
name                              0
last_season                       0
current_club_id                   0
player_code                       0
country_of_birth                  0
date_of_birth                     0
sub_position                      0
position_x                        0
foot                              0
height_in_cm                      0
market_value_in_eur               0
highest_market_value_in_eur       0
contract_expiration_date          0
agent_name                        0
game_event_id                  2470
type_x                            0
description                       0
season                            0
round                             0
date                              0
home_club_goals                   0
away_club_goals                   0
home_club_position                0
away_club_position                0
home_club_manager_name            0
away_club_manager_name            0
stadium                           0
attendance                        0
referee                           0
home_club_name                    0
away_club_name                    0
aggregate                         0
competition_type                  0
dtype: int64

In [76]:
df.columns

Index(['appearance_id', 'game_id', 'player_id_x', 'date_x', 'player_name_x',
       'competition_id_x', 'yellow_cards', 'red_cards', 'goals', 'assists',
       'minutes_played', 'name', 'last_season', 'current_club_id',
       'player_code', 'country_of_birth', 'date_of_birth', 'sub_position',
       'position_x', 'foot', 'height_in_cm', 'market_value_in_eur',
       'highest_market_value_in_eur', 'contract_expiration_date', 'agent_name',
       'game_event_id', 'type_x', 'description', 'season', 'round', 'date',
       'home_club_goals', 'away_club_goals', 'home_club_position',
       'away_club_position', 'home_club_manager_name',
       'away_club_manager_name', 'stadium', 'attendance', 'referee',
       'home_club_name', 'away_club_name', 'aggregate', 'competition_type'],
      dtype='object')

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3809 entries, 0 to 3808
Data columns (total 44 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   appearance_id                3809 non-null   object
 1   game_id                      3809 non-null   int64
 2   player_id_x                  3809 non-null   int64
 3   date_x                       3809 non-null   datetime64[ns]
 4   player_name_x                3809 non-null   object
 5   competition_id_x             3809 non-null   object
 6   yellow_cards                 3809 non-null   int64
 7   red_cards                    3809 non-null   int64
 8   goals                        3809 non-null   int64
 9   assists                      3809 non-null   int64
 10  minutes_played               3809 non-null   int64
 11  name                         3809 non-null   object
 12  last_season                  3809 non-null   int64
 13  current_club_id              3809 non-null   int64
 14  player_code                  3809 non-null   object
 15  country_of_birth             3809 non-null   object
 16  date_of_birth                3809 non-null   datetime64[ns]
 17  sub_position                 3809 non-null   object
 18  position_x                   3809 non-null   object
 19  foot                         3809 non-null   object
 20  height_in_cm                 3809 non-null   float64
 21  market_value_in_eur          3809 non-null   float64
 22  highest_market_value_in_eur  3809 non-null   float64
 23  contract_expiration_date     3809 non-null   datetime64[ns]
 24  agent_name                   3809 non-null   object
 25  game_event_id                1339 non-null   object
 26  type_x                       3809 non-null   object
 27  description                  3809 non-null   object
 28  season                       3809 non-null   int64
 29  round                        3809 non-null   object
 30  date                         3809 non-null   datetime64[ns]
 31  home_club_goals              3809 non-null   int64
 32  away_club_goals              3809 non-null   int64
 33  home_club_position           3809 non-null   float64
 34  away_club_position           3809 non-null   float64
 35  home_club_manager_name       3809 non-null   object
 36  away_club_manager_name       3809 non-null   object
 37  stadium                      3809 non-null   object
 38  attendance                   3809 non-null   float64
 39  referee                      3809 non-null   object
 40  home_club_name               3809 non-null   object
 41  away_club_name               3809 non-null   object
 42  aggregate                    3809 non-null   object
 43  competition_type             3809 non-null   object
dtypes: datetime64[ns](4), float64(6), int64(12), object(22)
memory usage: 1.3+ MB